# Game Scores
CORRECT_MOVE = "CORRECT_MOVE"
INVALID_MOVE = "INVALID_MOVE"
KILL = "KILL"
ARROW_MISS = "ARROW_MISS"
GET_ITEMS = "GET_ITEMS"
TIMEOUT = "TIMEOUT"
DEATH = "DEATH"

SCORES = {
    CORRECT_MOVE: 1000,
    INVALID_MOVE: -100,
    "GOLD": 10000,
    "DIAMOND": 60000,
    KILL: 15000,
    ARROW_MISS: 100,
    TIMEOUT: -1000
}
